<?php

namespace App\Filament\Resources\SaleResource\Pages;

use App\Filament\Resources\SaleResource;
use Filament\Actions;
use Filament\Actions\CreateAction;
use Filament\Resources\Pages\CreateRecord;
use Illuminate\Contracts\Support\Htmlable;

class CreateSale extends CreateRecord
{
    protected static string $resource = SaleResource::class;

    public function getTitle(): string|Htmlable
    {
        return '';// TODO: Change the autogenerated stub
    }

}
