<?php

namespace App\Filament\Resources\PurchaseResource\Pages;

use App\Filament\Resources\PurchaseResource;
use App\Models\PurchaseItem;
use App\Models\SaleItem;
use Filament\Actions;
use Filament\Actions\Action;
use Filament\Notifications\Notification;
use Filament\Resources\Pages\CreateRecord;
use Illuminate\Contracts\Support\Htmlable;

class CreatePurchase extends CreateRecord
{
    protected static string $resource = PurchaseResource::class;
    protected static bool $canCreateAnother=false;

    public function getTitle(): string|Htmlable
    {
        return '';// TODO: Change the autogenerated stub
    }
    protected function getFormActions(): array
    {
        return [
            Action::make('save')
                ->label('Iniciar Compra')
                ->color('success')
                ->icon('heroicon-o-check')
                ->action('create')
                ->extraAttributes([
                    'class' => 'alig', // Tailwind para ajustar el margen alinearlo a la derecha
                ]),

            Action::make('cancelSale')
                ->label('Cancelar proceso')
                ->icon('heroicon-o-no-symbol')
                ->color('danger')
                ->requiresConfirmation()
                ->modalHeading('Confirmación!!')
                ->modalSubheading('¿Estás seguro de que deseas cancelar esta venta? Esta acción no se puede deshacer.')
                ->modalButton('Sí, cancelar la Compra')
                ->action(function (Actions\DeleteAction $delete) {
                    if (!$this->record) {
                        $this->redirect(static::getResource()::getUrl('index'));
                        return;
                    }


                    PurchaseItem::where('purchase_id', $this->record->id)->delete();
                    $this->record->delete();

                    $this->redirect(static::getResource()::getUrl('index'));

                }),
        ];
    }


}
