<?php

namespace App\Filament\Resources\PurchaseResource\Pages;

use App\Filament\Resources\PurchaseResource;
use Filament\Actions;
use Filament\Resources\Pages\EditRecord;
use Illuminate\Contracts\Support\Htmlable;
use Livewire\Attributes\On;

class EditPurchase extends EditRecord
{
    protected static string $resource = PurchaseResource::class;

    protected function getHeaderActions(): array
    {
        return [
            Actions\DeleteAction::make(),
        ];
    }
    protected function beforeSave()
    {
//        dd($this->data);

    }
    public function getTitle(): string|Htmlable
    {
        return '';// TODO: Change the autogenerated stub
    }
    protected function getListeners(): array
    {
        return array_merge(parent::getListeners(), [
            'refreshTotalAmount' => 'updateTotalAmount', // Escucha el evento y ejecuta updateTotalAmount
        ]);
    }

    public function updateTotalAmount($totalAmount)
    {
        // Actualiza el valor de total_amount en tiempo real
        $this->form->fill([
            'total_amount' => $totalAmount,
        ]);
    }
    #[On('refreshPurchase')]
    public function refresh(): void
    {
    }
}
